### ISSUE TITLE
Recognize links that are not expressed as markdown

### ISSUE THREAD

**Issue by tanya-coding** [atomist/slack-messages#16]
@tanya-coding commented on [Fri Jul 28 2017](https://github.com/atomist/github-rugs/issues/61)

When links are not represented as markdown we don't show them as link in slack:

![image](https://user-images.githubusercontent.com/19268924/28719765-b2adcd96-7370-11e7-8b4d-c6d48e043c38.png)

**Comment by ddgenome** [comment]
I've started work on this.

**Comment by ddgenome** [comment]
According to the [Slack API message formatting documentation](https://api.slack.com/docs/message-formatting#linking_to_urls), they already do this.
