### ISSUE TITLE
GitHub markdown to Slack markup conversion has issues

### ISSUE THREAD

**Issue by ddgenome** [atomist/slack-messages#17]
There are several issues with the implementation of `githubToSlack`.

-   The backticks for code blocks, ` ```block``` `, must be at the beginning of lines.
-   Underscores are not recognized as valid bold and italic markers
-   Named links are not supported
-   #16 

There may be other issues. Review and fix.

https://guides.github.com/features/mastering-markdown/

**Comment by tanya-coding** [comment]
@ddgenome can you add an example where underscores where not properly converted to italic in Slack? markdown conversion should be handling them already, here is example of it working:

![image](https://user-images.githubusercontent.com/19268924/29217644-07c09b58-7e78-11e7-8381-540cc7bed702.png)

**Comment by tanya-coding** [comment]
@ddgenome can you expand on "The backticks for code blocks, ```block```, must be at the beginning of lines."? Github markdown will allow them to show up not on new line and will render them as code blocks, for example:

some text ```code block``` more text

**Comment by ddgenome** [comment]
In the code, I did not see that `_` were being properly replace, but I could have missed it.

I would guess the triple-backtick in a line works because it parses it as three separate single backtick segments. This ```code``` gets rendered as <code>code</code> while this

```
code block
```

gets rendered as <pre>.

**Comment by tanya-coding** [comment]
We can tweak triple tick block that is not on new line to behave like GH (converting to single code block effectively)

**Comment by tanya-coding** [comment]
@ddgenome the reason you didn't see "_" converted is because they actually don't need to be converted - that's what Slack uses for italic text so we are only conversing `**` and `*`

**Comment by ddgenome** [comment]
Not exactly right? In Markdown, double underscore or double asterisk if bold. Single underscore or single asterisk is italic. In markdown, underscore is italic and asterisk is bold, no doubles.

**Comment by ddgenome** [comment]
This is the code I am talking about:

https://github.com/atomist/slack-messages/blob/e4c90cac62e3fafea5d949637ba0ec615c3cac9e/src/Markdown.ts#L82-L89

I don't see a conversion from double underscore to single asterisk.

**Comment by ddgenome** [comment]
Some testing

_italic_ *italic* _ not italic _ * not italic * *%italic%* _¡italic!_

__bold__ **bold** __ not bold __ ** not bold ** __%bold%__ **¡bold!**

- first item
- second item

other

  - indented first item
  - indented second item

other

    - four space indent 1
    - four space indent 2

other

- item one
- item two
 - one space one
 - one space two
  - two space one
  - two space two

other

- item one
- item two
  - two space one
  - two space two

other

1. item 1
1. item 2

other

  1. two space 1
  1. two space 2

other

    1. four space indent 1
    1. four space indent 2

other

1. item one
1. item two
 1. one space one
 1. one space two
  1. two space one
  1. two space two

other

1. item one
1. item two
  1. two space one
  1. two space two

other

1. item one
1. item two
    1. four space one
    1. four space two

**Comment by ddgenome** [comment]
Released in 0.8.0
