### ISSUE TITLE
Remove dependency to @atomist/rug

### ISSUE THREAD

**Issue by cdupuis** [atomist/slack-messages#26]
For the future we need this module to be stand-alone. Or even define the Message types that are relevant for Slack. Maybe we should move `ResponseMessage`, `DirectedMessage` and `UpdatableMessage` over to here.

**Comment by cdupuis** [comment]
@kipz and @tanya-coding we should discuss this.

**Comment by ddgenome** [comment]
I was in this code so I am going to take a crack at this and submit a PR.

**Comment by ddgenome** [comment]
I've removed the compile time dependency, see https://github.com/atomist/slack-messages/compare/remove-rug-26?expand=1 .

How would you like the runtime dealt with? Should we bring in some kafka library and post to the appropriate channel? Should that be done here or someone else? How to deal with auth?

**Comment by ddgenome** [comment]
Done and released.
