### ISSUE TITLE
Truncating commit message can mess up escaping of special characters

### ISSUE THREAD

**Issue by tanya-coding** [atomist/slack-messages#35]
We might want to truncate first and then escape instead.

**Example:**

Original message (redacted):
`Zzz zzzzzzzz zzzzzzzz zzzzzz zzzzzzzzzz -> zzzzzz-> zzz zzzzzzz`

Truncated:
`Zzz zzzzzzzz zzzzzzzz zzzzzz zzzzzzzzzz -> zzzzzz-&gt...`

**Comment by ddgenome** [comment]
There is no truncating occurring in this library. This probably belongs in lifecycle-automation.

**Comment by ddgenome** [comment]
And this was greatly improved there.
