### ISSUE TITLE
Hyperlinks containing __something__ are mangled incorrectly

### ISSUE THREAD

**Issue by cdupuis** [atomist/slack-messages#36]
Issue moved from atomist/lifecycle-automation#232

Created by @kipz at 2018-07-03T09:25:50Z:

The following link:

https://github.com/graphql/graphql-js/blob/master/src/utilities/__tests__/buildClientSchema-test.js#L821

Get's rendered in slack like this:

https://github.com/graphql/graphql-js/blob/master/src/utilities/*tests*/buildClientSchema-test.js#L821

and can't be followed (link broken too)

---
Comment by @cdupuis at 2018-07-03T10:17:02Z:

I think that is actually a bug in the markdown conversation of `slack-messages`.

**Comment by ddgenome** [comment]
valid_markup_skip
valid__markup__skip
valid*markup*parse
valid**markup**parse

**Comment by ddgenome** [comment]
At some point we'll need to use a proper Markdown parser for this. This regular expression approach is getting a bit tedious.
