### ISSUE TITLE
Code within link names breaks Slack rendering

### ISSUE THREAD

**Issue by ddgenome** [atomist/slack-messages#37]
When using backticks within a link name, the Slack rendering is broken.

For example, this Markdown:

```markdown
- [`lib/api-helper/goal/storeGoals.ts:76`](https://github.com/atomist/sdm/blob/b01e992863d4e29f76a928494f09bf76fe15d0fc/lib/api-helper/goal/storeGoals.ts#L76): _(error)_ Type assertion on object literals is forbidden, use a type annotation instead.
```

ends up looking like this in Slack:

<img width="566" alt="markdown-slack-code-link" src="https://user-images.githubusercontent.com/57881/48554666-9d87bf80-e8a4-11e8-8030-792d26a16355.png">

**Comment by cdupuis** [comment]
Yeah, you need to put the back ticks around the url. That's how lifecycle does it. Inside the label formatting doesn't seem to work.

**Comment by ddgenome** [comment]
If I recall correctly, it's due to a deficiency in they way we parse the messages. We split on inline code and code blocks before performing URL replacement.

**Comment by ddgenome** [comment]
Looking at the parser, I'm surprised putting backticks around the whole things works either.

**Comment by cdupuis** [comment]
Yeah, it doesn't. Around back ticks only work when calling the `url` function. So this in TS code works `codeLine(url("http://test.com", "Blake"))`

**Comment by ddgenome** [comment]
Unfortunately that is not an option here since we want good rendering in both the GitHub web UI and Slack.

**Comment by cdupuis** [comment]
Yeah, we would have to do a lot of re-writing.
