### ISSUE TITLE
I want to mark down parsing of slack message and wrapping those with HTML tags.

### ISSUE THREAD

**Issue by Allauvdheenbasha** [atomist/slack-messages#40]
there is 8 pre-formatted text style in slack. I want to wrap those with HTML tags based on multiple scenarios.

**Comment by ddgenome** [comment]
Could you provide more context and link to the eight pre-formatted Slack text styles?

**Comment by Allauvdheenbasha** [comment]
i have attched the preformatted text flows and scenarios for those 8 styles in below link

[Slack markdown text scenarios](https://slack2teamsmigration-my.sharepoint.com/:x:/g/personal/alem_slack2teamsmigration_onmicrosoft_com/EQD6Uvk_WT5DiIXyXOYofIkBnmK2dBOmDb4Qj0dnm2TMsw?e=P9ni95)

i have gone through source code, i have tested the regex pattern for bold, italic scenario, its not working. i need to acheieve this in C#.NET.

[Preformatted Text flows.xlsx](https://github.com/atomist/slack-messages/files/3050333/Preformatted.Text.flows.xlsx)
