### ISSUE TITLE
Escape may need to escape double quotes

### ISSUE THREAD

**Issue by ddgenome** [atomist/slack-messages#7]
I ran into an issue where a ListIssues from github-rugs returned a message that could not be rendered by the bot. The offending section of the message JSON was:

```javascript
    {
      "fallback": "#167: "Reference Documentation -> Rug -> Overview - Rug API documentation" link not working",
      ...
    }
```

The title of the issue had double quotes in it, which ended up not being escaped, making the JSON invalid. It doesn't look like the less than characters were escaped either, even though the escape method should be escaping them.

**Comment by ddgenome** [comment]
Perhaps escape should `JSON.stringify` its argument too?

**Comment by ddgenome** [comment]
Or perhaps use `escape` from underscore?

**Comment by tanya-coding** [comment]
@ddgenome I don't think new version of github-rugs that is using slack-messages is deployed yet anywhere so it's probably a bug in current version.  I'll verify

**Comment by tanya-coding** [comment]
I confirmed this wan an issue with old version of `github-rugs`
